[package]
name = "dojo_introspect"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.12.2"
scarb-version = "2.12.2"
repository = "https://github.com/dojoengine/dojo-introspect"


[tool.fmt]
sort-module-level-items = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[dependencies]
starknet = "2.13.1"

[dev-dependencies]
cairo_test = "2.12.2"

[lib]
path = "package/lib.cairo"

[[target.starknet-contract]]
sierra = true
casm = false
